image_width: 1920
image_height: 1280
camera_name: usb_camera_rear
camera_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 960, 0, 1, 640, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0, 0, 0, 0, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [1, 0, 960, 0, 0, 1, 640, 0, 0, 0, 1, 0]
