sensor_kit_base_link:
  vlp32c:
    x: 0.46
    y: 0.0
    z: 1.96
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: -0.67
    y: 0.03
    z: 1.81
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gnss_base_link:
    x: 0.83
    y: 0.0
    z: 1.69
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

